DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ NOCACHE ORDER;

DROP TABLE MEMBER_T;
CREATE TABLE MEMBER_T (
	MEMBER_NO   NUMBER              NOT NULL
  , ID          VARCHAR2(50 BYTE)   NOT NULL
  , NAME        VARCHAR2(50 BYTE)   NULL
  , EMAIL       VARCHAR2(50 BYTE)   NULL
  , GENDER      VARCHAR2(5 BYTE)    NULL
  , ADDRESS     VARCHAR2(50 BYTE)   NOT NULL
  , CONSTRAINT PK_MEMBER PRIMARY KEY(MEMBER_NO)
);